openapi: 3.0.1
info:
  title: BrightQuery API
  description: >-
    BrightQuery, Inc. ("BQ") is the leading provider of U.S. business
    information, including firmographics, financials, credit events, employment,
    and benefits information. BQ tracks all companies operating in the U.S. that
    file taxes and have one or more employees (including the owner). BQ sources
    all information from U.S. government filings, leveraging in particular
    regulatory filings with the IRS, DOL, and the SEC. Finally, BQ provides over
    5,000 fields, including company information, as well as aggregated
    statistics on industries, sectors, counties, states, and the U.S. economy
    overall.<br><br>This collection of APIs enables a client to search for a
    company using parameters such as company name, address, and website. BQ’s
    proprietary search algorithms utilize fuzzy matching to search and rank the
    results. For a complete list of all fields that BQ can provide, including
    detailed financials, please <a
    href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
    >click here</a>. Please <a
    href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
    here</a> to download the list of IRS industries, which is the primary
    industry classification system used by BQ.<br><br>Please contact <a
    href="mailto:sales@brightquery.com" >sales@brightquery.com</a> for sales and
    <a href="mailto:support@brightquery.com" >support@brightquery.com</a> for
    product support. You may also call 1-888-BQDATA1. Please visit <a
    href="https://brightquery.com" target="_blank">https://brightquery.com/</a>
    to learn more about BQ’s full suite of products, including bulk data
    feeds.<br><br>© 2021 BrightQuery, Inc. All rights reserved. Visit us at: <a
    href="https://brightquery.com"
    target="_blank">https://www.brightquery.com</a>. Contact us at: <a href="
    mailto:sales@brightquery.com">sales@brightquery.com</a>, <a
    href="mailto:support@brightquery.com" >support@brightquery.com</a> or
    1-888-BQDATA1. For the terms of use of BrightQuery data and products,
    including these APIs, please see the following link: <a
    href="https://brightquery.com/terms-of-use/" target="_blank">Terms of
    Use.</a>
    <!-- ReDoc-Inject: <security-definitions> -->
  version: 2.1.1
  x-logo:
    url: 'BQ-logo.png'
    altText: BQ logo
servers:
  - url: https://apigateway.brightquery.com/auth
tags:
  - name: BQ APIs
paths:  
  /advance-search/org:
    post:
      summary: Organization Search API
      tags:
        - Business Identity API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: ticker
          in: query
          description: TICKER of the Organization if it is public.
          schema:
            type: string
            example: "MSFT"
        - name: ticker_parent
          in: query
          description: TICKER of the Organization's parent holding company if the parent is publicly listed.
          schema:
            type: string
            example: "MSFT"
        - name: ticker_related
          in: query
          description: All TICKERs associated with the Organization if it is publicly listed.
          schema:
            type: string
            example: "MSFT"
        - name: lei
          in: query
          description: Legal Entity Identifier of the Organization.
          schema:
            type: string
            example: "7YNCQQNDK8FBM9BBTK25"
        - name: cik
          in: query
          description: Central Index Key (CIK) is a unique number issued by the SEC.
          schema:
            type: string
            example: "0001128928"
        - name: website
          in: query
          description: Link to the Organization's primary website.
          schema:
            type: string
            example: "1010data.com"
        - name: ein
          in: query
          description: Unique number issued by the IRS given to the Organization.
          schema:
            type: string
            example: "570384104"
        - name: linkedin_url
          in: query
          description: Organization Linkedin URL.
          schema:
            type: string
            example: "www.linkedin.com/flowers"
        - name: company_name
          in: query
          description: Name of Organization.
          schema:
            type: string
            example: "FLOWERS FOODS INC"
        - name: address
          in: query
          description: Address of Organization.
          schema:
            type: string
            example: "1919 Flowers Cir Thomasville, GA 31757"
      requestBody:
        required: true
        content:
          application/json:
            examples:
              'Scenario 1: Ticker ':
                description: Ticker.
                value:
                    ticker: 'MSFT'                    
              'Scenario 2: LEI ':
                description: LEI.
                value:
                  lei: '7YNCQQNDK8FBM9BBTK25'
              'Scenario 3: CIK ':
                description: CIK
                value:
                  cik: '0001128928'
              'Scenario 4: Website ':
                description: Website<br/><b>search universe</b> is mandatory
                value:
                  website: '1010data.com'
              'Scenario 5: EIN ':
                description: EIN.
                value:
                  ein: '570384104'
              'Scenario 6: LinkedIn URL':
                description: LinkedIn URL.
                value:
                  linkedin_url: 'www.linkedin.com/flowers'
              'Scenario 7: Name ':
                description: Company name (fuzzy search)
                value:
                  company_name: 'Flower'
              'Scenario 8: Name, Website':
                description: Company name (fuzzy search) and website extact match
                value:
                  company_name: 'Flower'
                  website: 'flowersfoods.com'
              'Scenario 8: Name, Address':
                description: Company name (fuzzy search) and Address match
                value:
                  company_name: 'Flower'
                  website: '1919 Flowers Cir'
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search_org_res_200'          
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_400'
              examples:
                'Bad Request, example 1':
                  value:
                    message: Invalid request body
                'Bad Request, example 2':
                  value:
                    message: Invalid search parameters
                    
        '401':
          description: Authorization header is missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_401'
      security:
        - basicAuth: []
  /advance-search/le:
    post:
      summary: Legal Entity Search API
      tags:
        - Business Identity API
      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      requestBody:
        required: true
        description: Operation requires authorization header.
        content:
          application/json:
            # schema:
              # $ref: '#/components/schemas/search'
            examples:
              'Scenario 1: Ticker ':
                description: Ticker.
                value:
                    ticker: 'MSFT'
                    
              'Scenario 2: LEI ':
                description: LEI.
                value:
                  lei: '7YNCQQNDK8FBM9BBTK25'
                  search_universe: 'org'
              'Scenario 3: CIK ':
                description: CIK
                value:
                  cik: '0001128928'
                  search_universe: 'org'
              'Scenario 4: Website ':
                description: Website<br/><b>search universe</b> is mandatory
                value:
                  website: '1010data.com'  
                  search_universe: 'org'
              'Scenario 5: EIN ':
                description: EIN.
                value:
                  ein: '570384104'
                  search_universe: 'org'
              'Scenario 6: LinkedIn URL ':
                description: LinkedIn URL.
                value:
                  linkedin_url: ''
                  search_universe: 'org'
              'Scenario 7: Name ':
                description: Company name (fuzzy search)
                value:
                  name: 'Flower'
                  search_universe: 'org'
              'Scenario 8: Name, Website':
                description: Company name (fuzzy search) and website extact match
                value:
                  name: 'Flower'
                  website: 'flowersfoods.com'
                  search_universe: 'org'
              'Scenario 8: Name, Address':
                description: Company name (fuzzy search) and Address match
                value:
                  name: 'Flower'
                  website: '1919 Flowers Cir'
                  search_universe: 'org'
      responses:
        '200':
          description: Successful Operation
          # content:
          #   application/json:              
        '400':
          description: Bad Request
          # content:
          #   application/json:              
              # examples:
              #   Bad Request, example 1:
              #     value:
              #       message: Invalid request body
              #   Bad Request, example 2:
              #     value:
              #       message: Requested page (27) cannot be bigger than totalPages (22)
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /advance-search/officers:
    post:
      summary: Officers Search API
      tags:
        - Business Identity API
      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      requestBody:
        required: true
        description: Operation requires authorization header.
        content:
          application/json:
            # schema:
              # $ref: '#/components/schemas/search'
            examples:
              'Scenario 1: Ticker ':
                description: Ticker.
                value:
                    ticker: 'MSFT'
                    
              'Scenario 2: LEI ':
                description: LEI.
                value:
                  lei: '7YNCQQNDK8FBM9BBTK25'
                  search_universe: 'org'
              'Scenario 3: CIK ':
                description: CIK
                value:
                  cik: '0001128928'
                  search_universe: 'org'
              'Scenario 4: Website ':
                description: Website<br/><b>search universe</b> is mandatory
                value:
                  website: '1010data.com'  
                  search_universe: 'org'
              'Scenario 5: EIN ':
                description: EIN.
                value:
                  ein: '570384104'
                  search_universe: 'org'
              'Scenario 6: LinkedIn URL ':
                description: LinkedIn URL.
                value:
                  linkedin_url: ''
                  search_universe: 'org'
              'Scenario 7: Name ':
                description: Company name (fuzzy search)
                value:
                  name: 'Flower'
                  search_universe: 'org'
              'Scenario 8: Name, Website':
                description: Company name (fuzzy search) and website extact match
                value:
                  name: 'Flower'
                  website: 'flowersfoods.com'
                  search_universe: 'org'
              'Scenario 8: Name, Address':
                description: Company name (fuzzy search) and Address match
                value:
                  name: 'Flower'
                  website: '1919 Flowers Cir'
                  search_universe: 'org'
      responses:
        '200':
          description: Successful Operation
          # content:
          #   application/json:              
        '400':
          description: Bad Request
          # content:
          #   application/json:              
              # examples:
              #   Bad Request, example 1:
              #     value:
              #       message: Invalid request body
              #   Bad Request, example 2:
              #     value:
              #       message: Requested page (27) cannot be bigger than totalPages (22)
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /bq-append/org:
    post:
      summary: Organization Search & Append API
      tags:
        - KYB Append API
      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      requestBody:
        required: true
        description: Operation requires authorization header.
        content:
          application/json:
            # schema:
              # $ref: '#/components/schemas/search'
            examples:
              'Scenario 1: Ticker ':
                description: Ticker.
                value:
                    ticker: 'MSFT'
                    
              'Scenario 2: LEI ':
                description: LEI.
                value:
                  lei: '7YNCQQNDK8FBM9BBTK25'
                  search_universe: 'org'
              'Scenario 3: CIK ':
                description: CIK
                value:
                  cik: '0001128928'
                  search_universe: 'org'
              'Scenario 4: Website ':
                description: Website<br/><b>search universe</b> is mandatory
                value:
                  website: '1010data.com'  
                  search_universe: 'org'
              'Scenario 5: EIN ':
                description: EIN.
                value:
                  ein: '570384104'
                  search_universe: 'org'
              'Scenario 6: LinkedIn URL ':
                description: LinkedIn URL.
                value:
                  linkedin_url: ''
                  search_universe: 'org'
              'Scenario 7: Name ':
                description: Company name (fuzzy search)
                value:
                  name: 'Flower'
                  search_universe: 'org'
              'Scenario 8: Name, Website':
                description: Company name (fuzzy search) and website extact match
                value:
                  name: 'Flower'
                  website: 'flowersfoods.com'
                  search_universe: 'org'
              'Scenario 8: Name, Address':
                description: Company name (fuzzy search) and Address match
                value:
                  name: 'Flower'
                  website: '1919 Flowers Cir'
                  search_universe: 'org'
      responses:
        '200':
          description: Successful Operation
          # content:
          #   application/json:              
        '400':
          description: Bad Request
          # content:
          #   application/json:              
              # examples:
              #   Bad Request, example 1:
              #     value:
              #       message: Invalid request body
              #   Bad Request, example 2:
              #     value:
              #       message: Requested page (27) cannot be bigger than totalPages (22)
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /bq-append/le:
    post:
      summary: Legal Entity Search & Append API
      tags:
        - KYB Append API
      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      requestBody:
        required: true
        description: Operation requires authorization header.
        content:
          application/json:
            # schema:
              # $ref: '#/components/schemas/search'
            examples:
              'Scenario 1: Ticker ':
                description: Ticker.
                value:
                    ticker: 'MSFT'
                    
              'Scenario 2: LEI ':
                description: LEI.
                value:
                  lei: '7YNCQQNDK8FBM9BBTK25'
                  search_universe: 'org'
              'Scenario 3: CIK ':
                description: CIK
                value:
                  cik: '0001128928'
                  search_universe: 'org'
              'Scenario 4: Website ':
                description: Website<br/><b>search universe</b> is mandatory
                value:
                  website: '1010data.com'  
                  search_universe: 'org'
              'Scenario 5: EIN ':
                description: EIN.
                value:
                  ein: '570384104'
                  search_universe: 'org'
              'Scenario 6: LinkedIn URL ':
                description: LinkedIn URL.
                value:
                  linkedin_url: ''
                  search_universe: 'org'
              'Scenario 7: Name ':
                description: Company name (fuzzy search)
                value:
                  company_name: 'Flower'
                  search_universe: 'org'
              'Scenario 8: Name, Website':
                description: Company name (fuzzy search) and website extact match
                value:
                  name: 'Flower'
                  website: 'flowersfoods.com'
                  search_universe: 'org'
              'Scenario 8: Name, Address':
                description: Company name (fuzzy search) and Address match
                value:
                  name: 'Flower'
                  website: '1919 Flowers Cir'
                  search_universe: 'org'
      responses:
        '200':
          description: Successful Operation
          # content:
          #   application/json:              
        '400':
          description: Bad Request
          # content:
          #   application/json:              
              # examples:
              #   Bad Request, example 1:
              #     value:
              #       message: Invalid request body
              #   Bad Request, example 2:
              #     value:
              #       message: Requested page (27) cannot be bigger than totalPages (22)
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /extraction_api/firmographics:
    get:
      summary: Firmographics
      tags:
        - Extraction API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: bq_id
          in: query
          description: The starting date to retrieve future operating hours from. Defaults to today's date.
          schema:
            type: integer
            example: 100003273517
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /extraction_api/mr:
    get:
      summary: Financials - Most Recent(MR)
      tags:
        - Extraction API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: bq_id
          in: query
          description: The starting date to retrieve future operating hours from. Defaults to today's date.
          schema:
            type: integer
            example: 100003273517
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []  
  /extraction_api/ts:
    get:
      summary: Financials Time Series Annual (TS)
      tags:
        - Extraction API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: bq_id
          in: query
          description: The starting date to retrieve future operating hours from. Defaults to today's date.
          schema:
            type: integer
            example: 100003273517
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /extraction_api/tsq:
    get:
      summary: Financials Time Series Quartely (TSQ)
      tags:
        - Extraction API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: bq_id
          in: query
          description: The starting date to retrieve future operating hours from. Defaults to today's date.
          schema:
            type: integer
            example: 100003273517
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []
  /extraction_api/tsm:
    get:
      summary: Financials Time Series Monthly (TSM)
      tags:
        - Extraction API      
      description: >-
        The BQ Advanced Search API is generally suitable for clients in capital
        markets, investment banking, consulting, private equity, and venture
        capital. It is suitable for such purposes because the search results are
        biased in favor of large companies as well as public companies. That is,
        if two companies are equally matched to the search criteria entered by
        the user, then the BQ Advanced Search API ranks higher in the results
        the company that is larger or public. The BQ Advanced Search API is not
        suitable for users looking for small companies, such as those with less
        than 100 employees; such users should instead leverage the BQ Neutral
        Search API.<br><br> The BQ Advanced Search API enables a user to find a
        specific company. Searches can be performed using company name, address,
        website, and other firmographic criteria. The top 10 results are
        returned, including core firmographics (name, address, website, phone,
        industry, etc.), employment, revenue, and payroll. The results of the BQ
        Advanced Search API are sorted based on BQ’s proprietary match score
        which is weighted in favor of large companies.<br><br> The drop-down
        menu on the right provides a series of examples demonstrating how to use
        the BQ Advanced Search API. <br><br>Please refer to <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_Search_API_Data_Dictionary.xlsx"
        >BrightQuery_Search_API_Data_Dictionary</a> to obtain details of the
        attributes in API response. For a complete list of all fields that BQ
        can provide, including detailed financials, please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_data_dictionary.xlsx"
        >click here</a>. Please <a
        href="https://s3.us-west-1.amazonaws.com/docs.brightquery.com/BrightQuery_list+of+IRS+industries_subsector_sector_with_codes_Sep+2021.xlsx">click
        here</a> to download the list of IRS industries, which is the primary
        industry classification system used by BQ.<br><br>The average response
        time of the BQ Advanced Search API is 1 second.
      parameters:
        - name: bq_id
          in: query
          description: The starting date to retrieve future operating hours from. Defaults to today's date.
          schema:
            type: integer
            example: 100003273517
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Authorization header is missing or invalid
          # content:
          #   application/json:
      security:
        - basicAuth: []  
components:
  schemas:    
    search_org_res_200:
      type: object
      properties:
        root:
          type: object
          properties:
            id:
              type: string
              example: toplevel
            relevance:
              type: integer
              example: 1
            fields:
              type: object
              properties:
                totalCount:
                  type: integer
                  example: 10
            coverage:
              type: object
              properties:
                coverage:
                  type: integer
                  example: 100
                documents:
                  type: integer
                  example: 101316736
                full:
                  type: string
                  example: 'true'
                nodes:
                  type: integer
                  example: 10
                results:
                  type: integer
                  example: 1
                resultsFull:
                  type: integer
                  example: 1
            children:
              type: array
              items:
                type: object
                required:
                  - bq_organization_id
                  - bq_organization_name
                  - bq_organization_legal_name
                  - bq_organization_active_indicator
                  - bq_organization_address1_line_1
                  - bq_organization_address1_city
                  - bq_organization_address1_state
                  - bq_organization_address1_state_name
                  - bq_organization_address1_county_name
                  - bq_organization_address1_country
                  - bq_organization_address1_zip5
                  - bq_organization_address_summary
                  - bq_organization_website
                  - bq_organization_ein
                  - bq_organization_cik
                  - bq_organization_lei
                  - bq_organization_ticker
                  - bq_organization_naics_sector_name
                  - bq_legal_entity_id
                  - bq_legal_entity_name
                  - bq_legal_entity_address1_line_1
                  - bq_legal_entity_address1_city
                  - bq_legal_entity_address1_state
                  - bq_legal_entity_address1_zip5
                  - bq_organization_linkedin_url
                  - bq_tickers_related
                  - bq_ticker_parent
                  - bq_match_types
                  - bq_revenue_range
                  - bq_employment_range
                properties:
                  bq_organization_id:
                    type: string
                    example: '100003273517'
                  bq_organization_name:
                    type: string
                    example: FLOWERS FOODS INC
                  bq_organization_legal_name:
                    type: string
                    example: FLOWERS FOODS, INC
                  bq_organization_active_indicator:
                    type: integer
                    example: 1
                  bq_organization_address1_line_1:
                    type: string
                    example: 1919 Flowers Cir
                  bq_organization_address1_city:
                    type: string
                    example: Thomasville
                  bq_organization_address1_state:
                    type: string
                    example: GA
                  bq_organization_address1_state_name:
                    type: string
                    example: Georgia
                  bq_organization_address1_county_name:
                    type: string
                    example: Thomas County
                  bq_organization_address1_country:
                    type: string
                    example: United States
                  bq_organization_address1_zip5:
                    type: string
                    example: '31757'
                  bq_organization_address_summary:
                    type: string
                    example: 1919 Flowers Cir, Thomasville, Georgia GA, 31757
                  bq_organization_website:
                    type: string
                    example: https://flowersfoods.com/
                  bq_organization_ein:
                    type: string
                    example: '582582379'
                  bq_organization_cik:
                    type: string
                    example: '0001128928'
                  bq_organization_lei:
                    type: string
                    example: 7YNCQQNDK8FBM9BBTK25
                  bq_organization_ticker:
                    type: string
                    example: FLO
                  bq_organization_naics_sector_name:
                    type: string
                    example: Manufacturing
                  bq_legal_entity_id:
                    type: string
                    example: BQ_US_GA_0046273
                  bq_legal_entity_name:
                    type: string
                    example: FLOWERS FOODS, INC
                  bq_legal_entity_address1_line_1:
                    type: string
                    example: 1919 Flowers Cir
                  bq_legal_entity_address1_city:
                    type: string
                    example: Thomasville
                  bq_legal_entity_address1_state:
                    type: string
                    example: GA
                  bq_legal_entity_address1_zip5:
                    type: string
                    example: '31757'
                  bq_organization_linkedin_url:
                    type: string
                    example: https://www.linkedin.com/company/flowers-foods/
                  bq_tickers_related:
                    type: array
                  bq_ticker_parent:
                    type: string
                    example: ''
                  bq_match_types:
                    type: string
                    example: Name Only
                  bq_revenue_range:
                    type: string
                    example: '> $1 Billion'
                  bq_employment_range:
                    type: string
                    example: 500 - 10,000
        status:
          type: integer
          example: 200


    response_200:
      type: object
      properties:
        message:
          type: string
    response_400:
      type: object
      properties:
        message:
          type: string
          example: Invalid request body
    response_401:
      type: object
      properties:
        message:
          type: string
          example: Unauthorized          
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
